import React from "react";

export const content = {
    en: {
        navbar_home: "Home",
        navbar_about: "About us",
        navbar_custom: "Custom Made",
        navbar_catalog: "Catalog",
        navbar_contact: "Contact us",
        navbar_coll_b: "Collection B",
        navbar_coll_c: "Collection C",
        navbar_coll_d: "Collection D",
        navbar_coll_f: "Collection F",
        navbar_coll_h: "Collection H",
        navbar_coll_k: "Collection K",
        navbar_coll_l: "Collection L",
        navbar_coll_n: "Collection N",
        navbar_coll_r: "Collection R",
        navbar_coll_g: "Collection P, G",
        navbar_coll_s: "Collection S",
        navbar_coll_v: "Collection V",
        navbar_coll_w: "Collection W",
        navbar_coll_x: "Collection X",
        home_hero_title: "Traditions & Innovation",
        home_hero_subtitle: "Doing our best since 1992",
        about_hero_letter: "O",
        about_hero: "Our Story & Mission",
        custom_hero_letter: "M",
        custom_hero: "Made to Order",
        news_hero_letter: "W",
        news_hero: "What's new",
        catalog_hero_letter: "E",
        new_arr_letter: "N",
        catalog_hero: "Explore Our Collections",
        contacts_hero_letter: "C",
        contacts_hero: "Contact Us",
        error_hero_letter: "O",
        error_hero: "OOPS Page Not Found",
        coll_n_title: "Cylindrical and square vases",
        coll_d_title: "Cognac glass \n and \n sphere",
        coll_s_title: "Decanter, hookah",
        coll_k_title: "Cake maker, candy bar",
        coll_w_title: "Decorative floor vases",
        coll_f_title: "Candlestick",
        coll_l_title: "Lamps",
        coll_b_title: "Candy bars, fruit bowls",
        coll_c_title: "Vases of different configuration and purpose",
        coll_g_title: "Various purpose vases of coarse glass",
        coll_h_title: "Varietal tableware",
        coll_r_title: "Pressed tableware",
        coll_v_title: "Products with a lid; candy bar, fruit bowl",
        coll_x_title: "Sphere, cylinders, flower and interior vases",
        our_collections: "Our collections",
        design_your_item: "Design Your Item",
        design_your_item_letter: "D",
        about_us_title: "About us",
        our_story_title: "Our story",
        clients_title: "Clients in 10 countries!",
        trust_us: "You can trust us!",
        adv_handmade: "Hand-made products",
        adv_order: "Make to order",
        adv_experience: "27 years of experience",
        different_title: "Why we are different",
        questions: "Have questions?",
        contact_button: "Contact us",
        about_text_1: "We are always ready to incarnate projects in glass!\n" +
            "Producer of glass artistic items, and also technical colored glass. We specialize on art glassware in a wide range of shapes, designs, colours and sizes and make export to many countries. All items, clear or coloured, are mouth-blown and handmade. Moreover, our range of technological possibilities enable the individual production according to the client's requirements and orders.",
        about_text_2: "Our advantages:\n" +
            "- our company has technology of melting glass by electric oven;\n" +
            "- technologies for cooking and annealing of glass are environmentally friendly;\n" +
            "- we are in the process of building a solar station on the roofs of our factories;\n" +
            "- 25 years experience in supplying our products to all markets in many developed countries including China;\n" +
            "- very favorable placement – in the center of Europe we are close to our main customers.\n" +
            "- the factory is near the freeway what is good for logistics",
        design_text: "Our range of technological possibilities enable the individual production according to the\n" +
            "                            client's requirements and orders. We are always ready to incarnate all your ideas in glass!\n" +
            "                            Why not turn your fantasy into reality?",
        learn_more_button: "Learn more",
        explore_button: "Explore",
        pluses_experience: "years of experience",
        pluses_customers: "regular customers",
        pluses_countries: "partner-countries",
        new_arrivals_title: "New Arrivals",
        new_arrivals: "New arrivals",
        contact_us_title: "Contact us",
        custom_made_title: "Custom Made",
        our_works_title: "Our works",
        interested_title: "Interested?",
        order_now: "Order NOW",
        get_in_touch: "Get in touch",
        get_in: "Get in",
        touch: "touch",
        adress: "Lviv, Ukraine",
        name: "name*",
        email: "e-mail*",
        company: "company's name",
        choose_file: "Choose file",
        enter_mess: "Enter your message here...",
        country: "country",
        send_mess: "Send message",
        our_new_arrivals:"Our New Arrivals",
        industry_trends:"Industry trends",
        news_text: "You’re not going to find a more talented and professional group of glass art artists in one place. We are constantly creating something fresh and exciting to always stay in trend. Here you can see all our latest makings!",
        contacts_text :"Interested in our production or have any questions? Feel free to contact us through the form below! ",
        map_text_1: "Our professionalism is proved by our clients all over the world. We work\n" +
            "                            with the regular customers from France, Germany, Canada, Netherlands, China, Ukraine and\n" +
            "                            many others since 1992. Our clients are always our highest priority and we are constantly\n" +
            "                            improving to produce only the highest quality production for you. ",
        designing: "Designing",
        design_par: "Help with developing and designing your conception",
        tech_assisting: "Technical assisting",
        tech_assisting_par: "Help to choose the best manufacturing option for you",
        implementing:"Implementing",
        implementing_par: "Supporting at each step to the realisation",
        coarse_glass: "Coarse Glass Vase",
        flower_vase: "Flower Vase",
        custom_text: "When it comes to having a custom piece of glass made we will work with you to get you the piece of art glass you are looking for.  We will have the artist that is best suited to build your piece call you can talk with you.  We would love to see any drawings you have to help us see your vision and bring your glass idea to reality.\n" +
            "For more information or to schedule a consultation, please fill out the form at the bottom of the page"
    },
    ua: {
        navbar_home: "Головна",
        navbar_about: "Про нас",
        navbar_custom: "На замовлення",
        navbar_catalog: "Каталог",
        navbar_contact: "Контакти",
        navbar_coll_b: "Колекція B",
        navbar_coll_c: "Колекція C",
        navbar_coll_d: "Колекція D",
        navbar_coll_f: "Колекція F",
        navbar_coll_h: "Колекція H",
        navbar_coll_k: "Колекція K",
        navbar_coll_l: "Колекція L",
        navbar_coll_n: "Колекція N",
        navbar_coll_r: "Колекція R",
        navbar_coll_g: "Колекція P, G",
        navbar_coll_s: "Колекція S",
        navbar_coll_v: "Колекція V",
        navbar_coll_w: "Колекція W",
        navbar_coll_x: "Колекція X",
        home_hero_title: "Традиції & Іновації",
        home_hero_subtitle: "Втілюємо Ваші ідеї з 1992 року",
        about_hero_letter: "Н",
        about_hero: "Наша історія та місія",
        custom_hero_letter: "I",
        custom_hero: "Індивідуальні рішення",
        news_hero_letter: "H",
        news_hero: "Новинки",
        catalog_hero_letter: "Н",
        catalog_hero: "Наші колекції",
        contacts_hero_letter: "Я",
        contacts_hero: "Як зв'язатись",
        error_hero_letter: "У",
        new_arr_letter: "Н",
        error_hero: "Упс Сторінку не знайдено",
        coll_n_title: "Вази: циліндричні, квадратні",
        coll_d_title: "Кон'ячний бокал, куля",
        coll_s_title: "Декантер, кальян",
        coll_k_title: "Тортівниці, фруктівниці, кенді бар",
        coll_w_title: "Підлогові декоративні вази",
        coll_f_title: "Підсвічник",
        coll_l_title: "Світильники",
        coll_b_title: "Фруктовниці, цукерниці, ковпаки",
        coll_c_title: "Вази різної конфігурації та призначення",
        coll_g_title: "Вази різного призначення із грубого скла",
        coll_h_title: "Сортовий посуд",
        coll_r_title: "Прес вироби",
        coll_v_title: "Вироби із кришкою, кенді бар, фруктовниці",
        coll_x_title: "Кулі, циліндри, вази для квітів та інтер'єру",
        our_collections: "Наші колекції",
        design_your_item: "Щось особливе",
        design_your_item_letter: "Щ",
        about_us_title: "Про нас",
        our_story_title: "Наша історія",
        clients_title: "Клієнти в 10 країнах",
        trust_us: "Ви можете нам довіряти!",
        different_title: "Чому саме ми",
        adv_handmade: "Ручна робота",
        adv_order: "Робимо на замовлення",
        adv_experience: "27 років замовлення",
        questions: "Залишились питання?",
        about_text_1: "Ми завжди готові втілити проекти у склі!\n" +
            "Виробник скляних художніх предметів, а також технічного кольорового скла. Ми спеціалізуємось на художньому скляному посуді в широкому діапазоні форм, дизайну, кольорів та розмірів і здійснюємо експорт у багато країн. Усі предмети, прозорі або кольорові, видуті з рота та ручної роботи. Крім того, наш спектр технологічних можливостей дає можливість індивідуального виробництва відповідно до вимог та замовлень клієнта.",
        about_text_2: "Наші переваги:\n" +
            "- наша компанія має технологію плавлення скла електричною духовкою;\n" +
            "- технології приготування та відпалу скла є екологічно чистими;\n" +
            "- ми зараз будуємо сонячну станцію на дахах наших фабрик;\n" +
            "- 25-річний досвід постачання нашої продукції на всі ринки багатьох розвинених країн, включаючи Китай;\n" +
            "- дуже вигідне розміщення - в центрі Європи ми наближені до наших основних клієнтів.\n" +
            "- завод знаходиться біля автостради, що добре для логістики",
        design_text: "Наш спектр технологічних можливостей дає можливість індивідуального виробництва відповідно до вимоги та замовлення клієнта. Ми завжди готові втілити всі ваші ідеї у склі! Чому б не перетворити свою фантазію в реальність?",
        learn_more_button: "Детальніше",
        explore_button: "Дізнатись",
        pluses_experience: "років досвіду",
        pluses_customers: "постійних клієнтів",
        pluses_countries: "країн-партнерів",
        new_arrivals_title: "Новинки",
        new_arrivals: "Новинки",
        contact_us_title: "Зв'язатись",
        custom_made_title: "На замовлення",
        our_works_title: "Наші роботи",
        interested_title: "Цікавить?",
        order_now: "Замовити",
        get_in_touch: "Контакти",
        get_in: "Зв'яжіться",
        touch: "з нами",
        adress: "Львів, Україна",
        name: "Ім'я*",
        email: "e-mail*",
        company: "Назва компанії",
        choose_file: "Виберіть файл",
        enter_mess: "Введіть повідомлення...",
        country: "Країна",
        send_mess: "Надіслати",
        our_new_arrivals: "Наші новинки",
        industry_trends:"Тренди індустрії",
        news_text: "Наша команда професіоналів постійно розвивається аби робити для Вас лише найкращу та найсучаснішу продукцію! ",
        contacts_text :"Маєте питання або хочете замовити нашу продукцію? Надішліть повідомлення і ми обов'язково Вам допоможемо",
        map_text_1: "Наш професіоналізм підтверджено клієнтами з усього світу, які довіряють нам. Ми співпрацюємо з постійними клієнтами з Канади, Китаю, Франції, Німеччини, Нідерландів, України та багатьма іншими. З 1992 року наші клієнти були і залишаються нашим приорітетом, тому при постійно розвиваємось аби виготовляти для Вас лише продукцію найвищої якості.",
        designing: "Проектування",
        design_par: "Допоможемо розробити дизайн за Вашим бажанням",
        tech_assisting: "Технічне консультування",
        tech_assisting_par: "Оберемо найкращий спосіб виготовлення аби досягти найвищої якості продукції",
        implementing: "Втілення у життя",
        implementing_par: "Супроводжуємо на кожномі етапі до втілення у життя",
        coarse_glass: "Ваза із грубого скла",
        flower_vase: "Ваза для квітів",
        custom_text: "Якщо йде мова про індивіальні вироби зі скла, ми завжди готові співпрацювати з Вами аби зробити саме те, чого Ви очікуєте. Ми підберемо найкращих майстрів, які зможуть втілити саме Ваші задумки. Якщо у Вас є креслення або малюнки Вашого задуму, Ви моєете надіслати їх нам через контактну форму. Аби дізнатись більше, будь ласка, заповніть нашу форму для зв'язку. "

    }
};
