export const content = {
    en: {
        navbar_home: "Home",
        navbar_about: "About us",
        navbar_custom: "Custom Made",
        navbar_catalog: "Catalog",
        navbar_contact: "Contact us",
        navbar_coll_a: "Collection A",
        navbar_coll_b: "Collection B",
        navbar_coll_c: "Collection C",
        navbar_coll_d: "Collection D",
        navbar_coll_e: "Collection E",
        navbar_coll_f: "Collection F",
        navbar_coll_g: "Collection G",
        navbar_coll_h: "Collection H",
        navbar_coll_i: "Collection I",
        navbar_coll_j: "Collection J",
        navbar_coll_k: "Collection K",
        navbar_coll_l: "Collection L",
        navbar_coll_m: "Collection M",
        navbar_coll_n: "Collection N",
        navbar_coll_o: "Collection O",
        navbar_coll_p: "Collection P",
        home_hero_title: "Traditions & Innovation",
        home_hero_subtitle: "Doing our best since 1992",
        about_hero_letter: "O",
        about_hero: "Our Story & Mission",
        custom_hero_letter: "M",
        custom_hero: "Made to Order",
        news_hero_letter: "W",
        news_hero: "What's new",
        catalog_hero_letter: "E",
        catalog_hero: "Explore Our Collections",
        contacts_hero_letter: "C",
        contacts_hero: "Contact Us",
        error_hero_letter: "O",
        error_hero: "OOPS Page Not Found",
        coll_a_title: "Cylindrical and square vases",
        coll_b_title: "Cognac glass \n and \n sphere",
        coll_c_title: "Decanter, hookah",
        coll_d_title: "Cake maker, candy bar",
        coll_e_title: "Decorative floor vases",
        coll_f_title: "Candlestick",
        our_collections: "Our collections",
        design_your_item: "Design Your Item",
        design_your_item_letter: "D",
        about_us_title: "About us",
        our_story_title: "Our story",
        clients_title: "Clients in 10 countries!",
        trust_us: "You can trust us!",
        adv_handmade: "Hand-made products",
        adv_order: "Make to order",
        adv_experience: "27 years of experience",
        different_title: "Why we are different",
        questions: "Have questions?",
        contact_button: "Contact us",
        about_text_1: "We are always ready to incarnate projects in glass!\n" +
            "Producer of glass artistic items, and also technical colored glass. We specialize on art glassware in a wide range of shapes, designs, colours and sizes and make export to many countries. All items, clear or coloured, are mouth-blown and handmade. Moreover, our range of technological possibilities enable the individual production according to the client's requirements and orders.",
        about_text_2: "Our advantages:\n" +
            "- our company has technology of melting glass by electric oven;\n" +
            "- technologies for cooking and annealing of glass are environmentally friendly;\n" +
            "- we are in the process of building a solar station on the roofs of our factories;\n" +
            "- 25 years experience in supplying our products to all markets in many developed countries including China;\n" +
            "- very favorable placement – in the center of Europe we are close to our main customers.\n" +
            "- the factory is near the freeway what is good for logistics",
        design_text: "Our range of technological possibilities enable the individual production according to the\n" +
            "                            client's requirements and orders. We are always ready to incarnate all your ideas in glass!\n" +
            "                            Why not turn your fantasy into reality?",
        learn_more_button: "Learn more",
        explore_button: "Explore",
        pluses_experience: "years of experience",
        pluses_customers: "regular customers",
        pluses_countries: "partner-countries",
        new_arrivals_title: "New Arrivals",
        contact_us_title: "Contact us"

    },
    ua: {
        navbar_home: "Головна",
        navbar_about: "Про нас",
        navbar_custom: "На замовлення",
        navbar_catalog: "Каталог",
        navbar_contact: "Контакти",
        navbar_coll_a: "Колекція A",
        navbar_coll_b: "Колекція B",
        navbar_coll_c: "Колекція C",
        navbar_coll_d: "Колекція D",
        navbar_coll_e: "Колекція E",
        navbar_coll_f: "Колекція F",
        navbar_coll_g: "Колекція G",
        navbar_coll_h: "Колекція H",
        navbar_coll_i: "Колекція I",
        navbar_coll_j: "Колекція J",
        navbar_coll_k: "Колекція K",
        navbar_coll_l: "Колекція L",
        navbar_coll_m: "Колекція M",
        navbar_coll_n: "Колекція N",
        navbar_coll_o: "Колекція O",
        navbar_coll_p: "Колекція P",
        home_hero_title: "Традиції & Іновації",
        home_hero_subtitle: "Втілюємо Ваші ідеї з 1992",
        about_hero_letter: "Н",
        about_hero: "Наша історія та місія",
        custom_hero_letter: "I",
        custom_hero: "Індивідуальні рішення",
        news_hero_letter: "H",
        news_hero: "Новинки",
        catalog_hero_letter: "Н",
        catalog_hero: "Наші колекції",
        contacts_hero_letter: "Я",
        contacts_hero: "Як зв'язатись",
        error_hero_letter: "У",
        error_hero: "Упс Сторінку не знайдено",
        coll_a_title: "Вази: циліндрична, квадратна",
        coll_b_title: "Кон'ячний бокал, куля",
        coll_c_title: "Декантер, кальян",
        coll_d_title: "Тортівниця, фруктівниця, кенді бар",
        coll_e_title: "Підлогові декоративні вази",
        coll_f_title: "Підсвічник",
        our_collections: "Наші колекції",
        design_your_item: "Щось особливе",
        design_your_item_letter: "Щ",
        about_us_title: "Про нас",
        our_story_title: "Наша історія",
        clients_title: "Клієнти в 10 країнах",
        trust_us: "Ви можете нам довіряти!",
        different_title: "Чому саме ми",
        adv_handmade: "Ручна робота",
        adv_order: "Робимо на замовлення",
        adv_experience: "27 років замовлення",
        questions: "Залишились питання?",
        about_text_1: "Ми завжди готові втілити проекти у склі!\n" +
            "Виробник скляних художніх предметів, а також технічного кольорового скла. Ми спеціалізуємось на художньому скляному посуді в широкому діапазоні форм, дизайну, кольорів та розмірів і здійснюємо експорт у багато країн. Усі предмети, прозорі або кольорові, видуті з рота та ручної роботи. Крім того, наш спектр технологічних можливостей дає можливість індивідуального виробництва відповідно до вимог та замовлень клієнта.",
        about_text_2: "Наші переваги:\n" +
            "- наша компанія має технологію плавлення скла електричною духовкою;\n" +
            "- технології приготування та відпалу скла є екологічно чистими;\n" +
            "- ми зараз будуємо сонячну станцію на дахах наших фабрик;\n" +
            "- 25-річний досвід постачання нашої продукції на всі ринки багатьох розвинених країн, включаючи Китай;\n" +
            "- дуже вигідне розміщення - в центрі Європи ми наближені до наших основних клієнтів.\n" +
            "- завод знаходиться біля автостради, що добре для логістики",
        design_text: "Наш спектр технологічних можливостей дає можливість індивідуального виробництва відповідно до вимоги та замовлення клієнта. Ми завжди готові втілити всі ваші ідеї у склі! Чому б не перетворити свою фантазію в реальність?",
        learn_more_button: "Детальніше",
        explore_button: "Дізнатись",
        pluses_experience: "років досвіду",
        pluses_customers: "постійних клієнтів",
        pluses_countries: "країн-партнерів",
        new_arrivals_title: "Новинки",
        contact_us_title: "Зв'язатись"
    }
};
