export const content = {
    en: {
        navbar_home: "Home",
        navbar_about: "About us",
        navbar_custom: "Custom Made",
        navbar_catalog: "Catalog",
        navbar_contact: "Contact us",
        navbar_coll_a: "Collection A",
        navbar_coll_b: "Collection B",
        navbar_coll_c: "Collection C",
        navbar_coll_d: "Collection D",
        navbar_coll_e: "Collection E",
        navbar_coll_f: "Collection F",
        navbar_coll_g: "Collection G",
        navbar_coll_h: "Collection H",
        navbar_coll_i: "Collection I",
        navbar_coll_j: "Collection J",
        navbar_coll_k: "Collection K",
        navbar_coll_l: "Collection L",
        navbar_coll_m: "Collection M",
        navbar_coll_n: "Collection N",
        navbar_coll_o: "Collection O",
        navbar_coll_p: "Collection P",
        home_hero_title: "Traditions & Innovation",
        home_hero_subtitle: "Doing our best since 1992",
        about_hero_letter: "O",
        about_hero: "Our Story & Mission",
        custom_hero_letter: "M",
        custom_hero: "Made to Order",
        news_hero_letter: "W",
        news_hero: "What's new",
        catalog_hero_letter: "E",
        catalog_hero: "Explore Our Collections",
        contacts_hero_letter: "C",
        contacts_hero: "Contact Us",
        error_hero_letter: "O",
        error_hero: "OOPS Page Not Found"
    },
    ua: {
        navbar_home: "Головна",
        navbar_about: "Про нас",
        navbar_custom: "На замовлення",
        navbar_catalog: "Каталог",
        navbar_contact: "Контакти",
        navbar_coll_a: "Колекція A",
        navbar_coll_b: "Колекція B",
        navbar_coll_c: "Колекція C",
        navbar_coll_d: "Колекція D",
        navbar_coll_e: "Колекція E",
        navbar_coll_f: "Колекція F",
        navbar_coll_g: "Колекція G",
        navbar_coll_h: "Колекція H",
        navbar_coll_i: "Колекція I",
        navbar_coll_j: "Колекція J",
        navbar_coll_k: "Колекція K",
        navbar_coll_l: "Колекція L",
        navbar_coll_m: "Колекція M",
        navbar_coll_n: "Колекція N",
        navbar_coll_o: "Колекція O",
        navbar_coll_p: "Колекція P",
        home_hero_title: "Традиції & Іновації",
        home_hero_subtitle: "Втілюємо Ваші ідеї з 1992",
        about_hero_letter: "Н",
        about_hero: "Наша історія та місія",
        custom_hero_letter: "I",
        custom_hero: "Індивідуальні рішення",
        news_hero_letter: "H",
        news_hero: "Новинки",
        catalog_hero_letter: "Н",
        catalog_hero: "Наші колекції",
        contacts_hero_letter: "Я",
        contacts_hero: "Як зв'язатись",
        error_hero_letter: "У",
        error_hero: "Уупс Сторінку не знайдено"
    }
};
